### ISSUE TITLE
does not contain Content-Type: application/json

### ISSUE THREAD

**Issue by discobean** [PagerDuty/go-pagerduty#349] opened 2021-08-21 11:28 UTC
Hi,

I get invalid content-type when trying to run the pagerduty client.  It doesn't matter how much data I enter in `CreateIncidentOptions` the result is the same.

```
authtoken := "x"
client := pagerduty.NewClient(authtoken)
_, err := client.CreateIncident("test@example.com", &pagerduty.CreateIncidentOptions{})
if err != nil {
  log.Fatal(err)
}
```

```
2021/08/21 21:26:35 HTTP response with status code 502 does not contain Content-Type: application/json
exit status 1
```

**Comment by theckman** [comment] 2021-08-30 06:57
@discobean I took a look at this, and on the latest version (`v1.4.1`) I can't see a code path for that call that can result in the `Content-Type` header being missing.

**So that I can investigate further I'll need a bit more information: What version of Go are you using and how about the version of `go-pagerduty`?**

If you're curious, here is the code I traced showing the header should be set. The method you're calling makes its HTTP request here: https://github.com/PagerDuty/go-pagerduty/blob/e23b94cea01f37da371fd9d7efb4e20ea0e36ff2/incident.go#L202-L205

Which itself is a pretty short function that ends up calling `c.do()`: https://github.com/PagerDuty/go-pagerduty/blob/e23b94cea01f37da371fd9d7efb4e20ea0e36ff2/client.go#L271-L277 which itself calls `c.doWithEndpoint()`: https://github.com/PagerDuty/go-pagerduty/blob/e23b94cea01f37da371fd9d7efb4e20ea0e36ff2/client.go#L312-L314

Which we can see here sets the header correctly on line 306: https://github.com/PagerDuty/go-pagerduty/blob/e23b94cea01f37da371fd9d7efb4e20ea0e36ff2/client.go#L284-L310

**Comment by theckman** [comment] 2021-09-13 01:04
@discobean I'm realizing I misread your report, and after rereading it I'm very confident the issue isn't within this repo and so I'm inclined to close this issue.

So by default, when you use the Go PagerDuty REST client you should be making an HTTPS request right to their Layer 7 edge load balancers. We make an HTTPS request to them, and await a response. At a high level that's all this client does.

The error you're reporting indicates you're getting an HTTP 502 response when making the API call to PagerDuty, and the content of that response isn't `application/json`. The Go PagerDuty REST client will try to parse the error response from the PagerDuty API, but it does expect the error to be in JSON format and for the `Content-Type` HTTP header to indicate that. If that's not the case, the error returned by the client will be what you're reporting.

So at face value, what you're indicating is that the PagerDuty load balancer(s) are giving you an HTTP 502 response and the body isn't in a JSON format. There is nothing this library does that could influence that, and I wouldn't expect that to fail 100% of the time without PagerDuty showing an active incident on their status page, so this leads me to believe you've some local network configuration that's maybe causing problems.

That could either be some outbound proxy on the network failing to send requests to the PagerDuty API, or your local DNS recursive resolver is returning the wrong IPs for PagerDuty's API hostname. Does the issue also happen if you use `curl` to generate the request from the same machine?

If you do have some sort of network proxy or self-hosted recursive DNS resolver, you may want to verify with your Network Administrators that none of that is related. In case it helps, here is the snippet I used to unsuccessfully reproduce this issue:

```Go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/PagerDuty/go-pagerduty"
)

func main() {
	k := os.Getenv("PD_API_KEY")
	if len(k) == 0 {
		log.Fatal("PD_API_KEY must be set")
	}

	c := pagerduty.NewClient(k)

	o := &pagerduty.CreateIncidentOptions{
		IncidentKey: "foobar",
		Type:        "incident",
		Title:       "Static Test Incident",
		Service: &pagerduty.APIReference{
			Type: "service_reference",
			ID:   "PXT4TC7", // XXX: change this to be your service ID
		},
		Body: &pagerduty.APIDetails{
			Type:    "incident_body",
			Details: "test string",
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)

	defer cancel()

	// XXX: change this to be your email address
	i, err := c.CreateIncidentWithContext(ctx, "t@heckman.io", o)
	if err != nil {
		log.Fatalf("failed to create incident: %s", err)
	}

	fmt.Printf("%+v\n", i)
}
```

If there is any additional information you can share which might change that understanding, I'd be more than happy to reopen this issue and dig-in further.

**Closed** 2021-09-13 01:04 UTC
Labels: cannot reproduce

**Comment by discobean** [comment] 2021-09-17 02:13
I believe there was (or may have been) an outage/issue in pagerduty at some point and I was hitting this error.  Shortly afterwards without any changes it started to work.  And it is currently working right now.
